来自 debian：9.5-slim

LABEL  “ com.github.actions.name” = “世界你好” 
LABEL  “ com.github.actions.description” = “将参数写入标准输出” 
LABEL  “ com.github.actions.icon” = “麦克风” 
LABEL  “ com.github.actions.color“ = ”紫色“

LABEL  “ repository” = “ http://github.com/octocat/hello-world” 
LABEL  “ homepage” = “ http://github.com/actions” 
LABEL  “ maintainer” = “ Octocat <octocat@github.com> ”

添加 entrypoint.sh /entrypoint.sh
 运行 chmod + x /entrypoint.sh
 ENTRYPOINT [ “ /entrypoint.sh” ]
